import type { NodeDefinitionRegistry } from "./types";

export const nodeDefinitions: NodeDefinitionRegistry = {
	switch: {
		kind: "switch",
		displayName: "Switch",
		color: "#ffd166",
		minInputs: 0,
		maxInputs: 0,
		outputCount: 1,
		createDefaultData: () => ({ kind: "switch", value: false }),
		evaluate: (_inputs, data) => [data.kind === "switch" ? data.value : false],
	},
	buffer: {
		kind: "buffer",
		displayName: "Buffer",
		color: "#cdb4db",
		minInputs: 1,
		maxInputs: 1,
		outputCount: 1,
		createDefaultData: () => ({ kind: "buffer" }),
		evaluate: (inputs) => [inputs[0] ?? false],
	},
	not: {
		kind: "not",
		displayName: "Not",
		color: "#f4a261",
		minInputs: 1,
		maxInputs: 1,
		outputCount: 1,
		createDefaultData: () => ({ kind: "not" }),
		evaluate: (inputs) => [!(inputs[0] ?? false)],
	},
	and: {
		kind: "and",
		displayName: "And",
		color: "#8ecae6",
		minInputs: 2,
		maxInputs: null,
		outputCount: 1,
		createDefaultData: () => ({ kind: "and" }),
		evaluate: (inputs) => [inputs.length > 0 && !inputs.includes(false)],
	},
	or: {
		kind: "or",
		displayName: "Or",
		color: "#90be6d",
		minInputs: 2,
		maxInputs: null,
		outputCount: 1,
		createDefaultData: () => ({ kind: "or" }),
		evaluate: (inputs) => [inputs.includes(true)],
	},
	xor: {
		kind: "xor",
		displayName: "Xor",
		color: "#e76f51",
		minInputs: 2,
		maxInputs: null,
		outputCount: 1,
		createDefaultData: () => ({ kind: "xor" }),
		evaluate: (inputs) => [
			inputs.filter(Boolean).length % 2 === 1 && inputs.length > 0,
		],
	},
	boardInput: {
		kind: "boardInput",
		displayName: "Board Input",
		color: "#7bdff2",
		minInputs: 0,
		maxInputs: 0,
		outputCount: 1,
		createDefaultData: () => ({ kind: "boardInput", boardPortId: "" }),
		evaluate: () => [false],
	},
	boardOutput: {
		kind: "boardOutput",
		displayName: "Board Output",
		color: "#b8f2e6",
		minInputs: 1,
		maxInputs: 1,
		outputCount: 0,
		createDefaultData: () => ({ kind: "boardOutput", boardPortId: "" }),
		evaluate: () => [],
	},
};
